# Generated by Django 4.1 on 2022-09-04 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Userr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.IntegerField(unique=True, verbose_name="Telegram ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=datetime.datetime.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "username",
                    models.CharField(
                        max_length=32, verbose_name="Username from telegram"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=64, verbose_name="First name from telegram"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=64, verbose_name="Last name from telegram"
                    ),
                ),
                (
                    "avatar",
                    models.FilePathField(
                        path=pathlib.PurePosixPath(
                            "/home/nappy/Projects/Freelance/tg_social/media/avatars"
                        ),
                        verbose_name="The path to the user's avatar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="users",
                        to="account.userr",
                    ),
                ),
            ],
        ),
    ]
